all:
	gcc src/main.c src/fio.c src/process.c src/linkedList.c -Wall -std=c99 -pedantic -Iinclude -o bin/A2
self:
	nano Makefile
main:
	nano src/main.c
fio:
	nano src/fio.c
fioh:
	nano include/fio.h
List:
	nano src/linkedList.c
Listh:
	nano include/linkedList.h
process:
	nano src/process.c
processh:
	nano include/process.h
run:
	./bin/A2
