all:
	gcc src/main.c src/fio.c src/process.c src/linkedList.c -Wall -std=c99 -pedantic -Iinclude -o bin/A2
self:
	nano Makefile
main:
	nano -T4 -i src/main.c
fio:
	nano -T4 -i src/fio.c
fioh:
	nano -T4 -i include/fio.h
List:
	nano -T4 -i src/linkedList.c
Listh:
	nano -T4 -i include/linkedList.h
process:
	nano -T4 -i src/process.c
processh:
	nano -T4 -i include/process.h
run:
	./bin/A2 input.txt 0
input:
	nano input.txt
debug:
	./bin/A2 input.txt 1
