all:
	gcc src/A1.c src/pipe.c -Wall -pedantic -std=gnu99 -Iinclude -o src/A1
test:
	gcc src/signalExample.c -Wall -pedantic -std=gnu99 -Iinclude -o src/sigEx
testEdit:
	nano src/signalExample.c
testRun:
	./src/sigEx
testRunBg:
	./src/sigEx &
self:
	nano Makefile
run:
	./src/A1
main:
	nano src/A1.c
header:
	nano include/pipe.h
fio:
	nano src/fio.c
text:
	nano test.txt
pipe:
	nano src/pipe.c
